import logging
from typing import List
from google import genai
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception
from app.core.config import settings

# Initialize logger for production monitoring
logger = logging.getLogger(__name__)

# Unified client configuration forcing the latest stable API version
# v1 supports the Gemini 2.x production-ready model series
client = genai.Client(
    api_key=settings.GEMINI_API_KEY,
    http_options={'api_version': 'v1'}
)

def is_rate_limit_error(exception: Exception) -> bool:
    """Checks if the exception is a 429 Rate Limit error."""
    return "429" in str(exception)

@retry(
    wait=wait_exponential(multiplier=1, min=1, max=4), 
    stop=stop_after_attempt(2),
    retry=retry_if_exception(is_rate_limit_error),
    before_sleep=lambda retry_state: logger.warning(
        f"Rate limit hit. Retrying AI call... Attempt {retry_state.attempt_number}"
    )
)
def fetch_ai_response(model_name: str, prompt: str) -> str:
    """
    Executes a direct call to the Gemini API with exponential backoff for rate limits.
    
    Args:
        model_name (str): The specific Gemini model identifier.
        prompt (str): The formatted prompt sent to the LLM.

    Returns:
        str: The generated text response from the model.

    Raises:
        ValueError: If the model returns an empty or invalid response.
    """
    response = client.models.generate_content(
        model=model_name,
        contents=prompt
    )
    
    if response and response.text:
        return response.text.strip()
    
    raise ValueError(f"Model {model_name} returned an empty response.")

def generate_safe_answer(prompt: str) -> str:
    """
    Orchestrates AI generation with a robust fallback mechanism.
    It attempts to use premium models first, falling back to lighter 
    versions if the primary model fails.

    Args:
        prompt (str): The complete context and question for the AI.

    Returns:
        str: The final answer generated by the first available model.

    Raises:
        RuntimeError: If all configured models fail to respond.
    """
    # 2026 Model Roadmap: Priority on Flash 2.5 for accuracy, 
    # falling back to Flash-Lite for speed and cost-efficiency.
    models_to_try: List[str] = [
        "gemini-2.5-flash", 
        "gemini-2.5-flash-lite"
    ]

    for model_name in models_to_try:
        try:
            logger.info(f"Attempting to generate answer using model: {model_name}")
            return fetch_ai_response(model_name, prompt)
        except Exception as e:
            # Capture specific error details while masking sensitive info
            logger.error(f"Provider failure for {model_name}: {str(e)[:150]}")
            continue
            
    raise RuntimeError("Critical: All AI models failed. Verify API quota and service status.")